### ISSUE TITLE
error during setup

### ISSUE THREAD

**Issue by justinw78** [ksya/ha-nefiteasy#1]
I think im doing something wrong??

maybe someone knows the solution?

Error during setup of component nefiteasy
Traceback (most recent call last):
  File "/config/custom_components/nefiteasy/__init__.py", line 91, in connect
    await asyncio.wait_for(self.nefit.xmppclient.connected_event.wait(), timeout=15.0)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 168, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/nefiteasy/__init__.py", line 57, in async_setup
    await client.connect()
  File "/config/custom_components/nefiteasy/__init__.py", line 101, in connect
    raise PlatformNotReady
homeassistant.exceptions.PlatformNotReady

Greetings justin

**Comment by ThaNarie** [comment]
I had the same error, and although most answers are leading to an SSL error, that's not the case in this scenario.

For me it helped by changing the connection timeout from `15` to `30` seconds in:
https://github.com/ksya/ha-nefiteasy/blob/276d6fee7860cac581fea9ee7a89637198a09958/__init__.py#L91

Currently it seems like a race condition between the XMPP connection duration and an arbitrary value for the timeout. 😄

It seems like the `aionefit` client isn't sending any 'connected' event from their `session_start` event:
https://github.com/marconfus/aionefit/blob/2dc1da4a562980f785638fda7a7d8eb0ac4883ff/aionefit/provider/slixmpp_impl.py#L47-L52

Which would be useful in this case, but without that, I would suggest to increase the wait timeout, or build in a re-check mechanism. 🙂

**Comment by Funky6ft6** [comment]
Hi, thanks for sharing! For me, ThaNarie's suggestion did not work. I'll try do both SSL and timeout increase.

**Comment by Funky6ft6** [comment]
If you are running home assistant in a docker container, then you'll have to pass the right config file for openssl to the docker image. 

You can do thisby:
1. copying the systemwide openssl.cnf file to the mounted /config folder 
2. place the suggested parameters in the top of the openssl.cnf file.
3. edit the systemd start command for the home assistant docker run command, which in my case is placed in the /etc/systemd/system foilder:under the rare name of `homeassistant@home-assistant.service`
`ExecStart=/usr/bin/docker run -e "OPENSSL_CONF=/config/openssl.cnf" --name=home-assistant-%i -v /home/%i/.homeassistant/:/config -v /etc/localtime:/etc/localtime:ro --net=host homeassistant/raspberrypi3-homeassistant:stable
`
