### ISSUE TITLE
thermostat card always shows a 'fire' icon

### ISSUE THREAD

**Issue by pathia** [ksya/ha-nefiteasy#106]
the thermostat card of my 'cv ketel' is always showing a lit 'fire' icon as if it is continuously heating.
I'm not really sure what the underlying entity name for that is so I don't know how to debug this.
(by the way the Nefit Easy app and the physical thermostat unit are not showing this heating icon continuously)
![image](https://user-images.githubusercontent.com/126187/150215973-5e611562-b26e-477f-83df-7b21911daa9b.png)

**Comment by RobBie1221** [comment]
The fire icon represents the `HVAC` mode. Only one mode is supported, which is `HVAC_MODE_HEAT`. You automatically get the fire icon with this mode. Other modes are for example COOL, DRY, FAN_ONLY. Nothing much I can do about that.

**Comment by pathia** [comment]
Hi Rob, thanks for the clarification. I confused the fire icon with the almost identical icon in the nefit easy app which over there tells whether or not the cv ketel is actually currently heating or not.
For example my airconditioning has (among others) an off and a fire icon. If the cv ketel is not currently heating in my opinion it could be in the off state in home assistant.

**Comment by RobBie1221** [comment]
The problem is that `HVAC_MODE` is a representation of the operation mode and not of the actual status. An airconditioning you can switch off, the nefit has no off switch.

If you are unhappy with this, you should adress your comments to the home assistant core. This integration is simply using what's available.
