### ISSUE TITLE
Warning:  implements device_state_attributes. 

### ISSUE THREAD

**Issue by felix63** [ksya/ha-nefiteasy#113]
"home_assistant": {
"installation_type": "Home Assistant Container",
"version": "2022.2.2",
"dev": false,
"hassio": false,
"virtualenv": false,
"python_version": "3.9.7",
"docker": true,
"arch": "x86_64",
"timezone": "Europe/Amsterdam",
"os_name": "Linux",
"os_version": "5.11.0-41-generic",
"run_as_root": true
}

`Entity climate.nefit (<class 'custom_components.nefiteasy.climate.NefitThermostat'>) implements device_state_attributes. Please report it to the custom component author.`

**Comment by RobBie1221** [comment]
Are you not on the latest version of the integration?

**Comment by felix63** [comment]
I wasn't. For some reason the repository for nefiteasy was not in my hacs. So I missed a couple of updates. Sorry!

**Comment by felix63** [comment]
But I now get other warnings:
`Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:259 
Integration: Sensor (documentation, issues) 
First occurred: 20:45:10 (1 occurrences) 
Last logged: 20:45:10

sensor.nefit_year_total has unit m3 which is unsupported for device_class gas`

**Comment by RobBie1221** [comment]
Can you crosscheck `const.py` with what's in this Github repo, especially the year total entry? It takes `VOLUME_CUBIC_METER` from HA, that should nog take m3 but m with upper 3.

**Comment by RobBie1221** [comment]
And can you double check the unit when checking state of entity?

**Comment by felix63** [comment]
My const.py is identical except for these lines that are not in my version:
AUTH_ERROR_PASSWORD = "auth_error_password"
AUTH_ERROR_CREDENTIALS = "auth_error_credentials"

The entity reports:
total
18 minutes ago
Last changed:
18 minutes ago
Last updated:
18 minutes ago
495,6 m³


I've restarted Home-assistant again. So far the warning has not repeated. I'll keep an eye out. But for now thanks very much for your prompt replies and sorry to have bothered you for something that was not really an issue.
