### ISSUE TITLE
sensor.boiler_indicator gone?

### ISSUE THREAD

**Issue by sweetpants** [ksya/ha-nefiteasy#129]
Am i right that the sensor.boiler_indicator is gone?
What's the replacement sensor?

**Comment by RobBie1221** [comment]
Was there ever a sensor.boiler_indicator? Is that a self-assigned entity name? What information was this entity exposing?

Which version did you still have the sensor?

**Comment by sweetpants** [comment]
As far as I know there was a sensor with this name. The values it supplied where
CH - Central Heating Active
HW - Hot Water Active
and a few other states

![image](https://user-images.githubusercontent.com/23421160/162187801-70cbc02d-7167-4243-adf7-2cba508cc95f.png)


This morning I upgraded HA to 2022.4.0 and since that time I get 'unknown'

**Comment by sweetpants** [comment]
I have a custom integration that relies on this sensor so i know when to turn on/off my central heating pump (when this sensor goes to state CH). In the log of this integration i can see it stopped right after the upgrade of HA to 2022.4.0. Not sure if this is related. In the Nefit Easy integration entities I don't see this sensor either/anymore.

**Comment by sweetpants** [comment]
Looks like it has something to do with nefit.climate device

**Comment by sweetpants** [comment]
The code is still there

@property
    def hvac_action(self) -> str:
        """Return the current running hvac operation if supported."""
        if (
            self.coordinator.data.get("boiler_indicator") == "CH"
        ):  # HW (hot water) is not for climate
            return CURRENT_HVAC_HEAT

        return CURRENT_HVAC_IDLE

**Comment by RobBie1221** [comment]
I'm trying to figure out what changed. I can't find any boiler indicator ever being defined in this integration. It should not change with HA version, as long as you don't update the integration...

**Comment by sweetpants** [comment]
I found the culpritt. There used to be a boiler_indicator supplied bij climate.nefit. This has disappeared  somehow. The climate.nefit now supplies hvac_acion which has values idle/heating. I have changed my custom integration to use that and now it works again. When heating is turned on, the circulation pump is turned on and when turned off, the pump is turned off after 10 minutes. issue closed
