### ISSUE TITLE
HACS compatibility 

### ISSUE THREAD

**Issue by sanderpleijers** [ksya/ha-nefiteasy#14]
Can you please make this component HACS compatible? (See https://hacs.xyz/)

**Comment by lvhv91** [comment]
@sanderpleijers, A pull request for HACS compatibility has been created :
[https://github.com/ksya/ha-nefiteasy/pull/16](url)

**Comment by ksya** [comment]
and is merged now

**Comment by TimSoethout** [comment]
Thank you all for making this work in HACS.

Maybe not the place, but been a silent user for this integration for over a year, just wanted to give a thumbs up.

**Comment by sanderpleijers** [comment]
Yeah! Thank you so much! :)
