### ISSUE TITLE
Can only update to version 0.2.1, any newer versions break

### ISSUE THREAD

**Issue by eppenga** [ksya/ha-nefiteasy#148]
Thanks for this great component!

FYI when I update I can only update to version 0.2.1, if I use a newer version I get this error message:

Logger: homeassistant.setup
Source: setup.py:178
First occurred: 09:02:16 (1 occurrences)
Last logged: 09:02:16

Setup failed for nefiteasy: Unable to import component: cannot import name 'SensorDeviceClass' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)

Versions 0.1.0 and 0.2.1 work fine, after that it breaks.

**Comment by RobBie1221** [comment]
Which home assistant version are you using?

**Comment by eppenga** [comment]
I am using "Home Assistant 2021.11.0":

## System Health

version | core-2021.11.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4985
Installed Version | 1.15.2
Stage | running
Available Repositories | 1045
Installed Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.03.5
docker_version | 20.10.8
disk_total | 28.6 GB
disk_used | 6.8 GB
healthy | true
supported | true
board | rpi3-64
supervisor_api | ok
version_api | ok
installed_addons | SSH & Web Terminal (10.1.1), Terminal & SSH (9.3.0), File editor (5.3.3)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 4
mode | storage

</details>

**Comment by RobBie1221** [comment]
Yes so that doesn’t work. The newest version of this integration is only guaranteed to work with newest Home Assistant version.

Some things got deprecated in December, so this error your getting is about a new class that hasn’t been there in November 2021 release. If you want the newest version, you need to upgrade HA.

**Comment by eppenga** [comment]
Thanks @RobBie1221, wasn't aware that it didn't auto update. Will do that and report back if it works. Thx & kr, Ebo
