### ISSUE TITLE
Deprecated attributes for Home Assistant 2022.10

### ISSUE THREAD

**Issue by dennisvdheuvel** [ksya/ha-nefiteasy#152]
custom_components.nefiteasy.models is setting deprecated attributes on an instance of NumberEntityDescription, this is not valid and will be unsupported from Home Assistant 2022.10.

Logger: homeassistant.config_entries
Source: custom_components/nefiteasy/__init__.py:107
Integration: Nefit Easy Bosch Thermostat (documentation, issues)
First occurred: 11:16:39 (1 occurrences)
Last logged: 11:16:39

Error setting up entry 717918861 for nefiteasy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/nefiteasy/__init__.py", line 44, in async_setup_entry
    client = NefitEasy(hass, credentials)
  File "/config/custom_components/nefiteasy/__init__.py", line 107, in __init__
    self.nefit = NefitCore(
  File "/usr/local/lib/python3.10/site-packages/aionefit/__init__.py", line 45, in __init__
    self.xmppclient = NefitXmppClient(jid=self.jid,
  File "/usr/local/lib/python3.10/site-packages/aionefit/provider/slixmpp_impl.py", line 32, in __init__
    self.register_plugin('xep_0280') #carbons
  File "/usr/local/lib/python3.10/site-packages/slixmpp/basexmpp.py", line 241, in register_plugin
    self.plugin.enable(plugin, pconfig)
  File "/usr/local/lib/python3.10/site-packages/slixmpp/plugins/base.py", line 165, in enable
    self.enable(dep, enabled=enabled)
  File "/usr/local/lib/python3.10/site-packages/slixmpp/plugins/base.py", line 165, in enable
    self.enable(dep, enabled=enabled)
  File "/usr/local/lib/python3.10/site-packages/slixmpp/plugins/base.py", line 153, in enable
    load_plugin(name)
  File "/usr/local/lib/python3.10/site-packages/slixmpp/plugins/base.py", line 82, in load_plugin
    __import__(module)
  File "/usr/local/lib/python3.10/site-packages/slixmpp/plugins/xep_0203/__init__.py", line 11, in <module>
    from slixmpp.plugins.xep_0203 import stanza
  File "/usr/local/lib/python3.10/site-packages/slixmpp/plugins/xep_0203/stanza.py", line 13, in <module>
    from slixmpp.plugins import xep_0082
  File "/usr/local/lib/python3.10/site-packages/slixmpp/plugins/xep_0082.py", line 12, in <module>
    from slixmpp.thirdparty import tzutc, tzoffset, parse_iso
  File "/usr/local/lib/python3.10/site-packages/slixmpp/thirdparty/__init__.py", line 7, in <module>
    from slixmpp.thirdparty.orderedset import OrderedSet
  File "/usr/local/lib/python3.10/site-packages/slixmpp/thirdparty/orderedset.py", line 25, in <module>
    class OrderedSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'

**Comment by RobBie1221** [comment]
Thanks for reporting. I’ll have a look at it.

**Comment by raybo2701** [comment]
same here. updated doesn't work anymore

**Comment by danieldotnl** [comment]
I did some research: 
The actual issue is that `MutableSet` was moved from the `collections` package, to `collections.abc`. Pretty simple to fix. However, the `MutableSet` is being used in the 'slixmpp' library, which is being used by 'aionefit', which is being used by 'ha-nefiteasy'. 
The actual issue has already been fixed in the 'slixmpp' library one year ago. Current release is 1.8.2, but 'aionefit' is still using 1.5.1. Extra complication might be that the 'aionefit' library seems not maintained anymore (it's publicly archived on Github). 

So my guess is, that all it takes is to upgrade aionefit to the latest slixmpp version. But since aionefit is archived, we can't create an issue there anymore. 
@RobBie1221 maybe you can clone 'aionefit'?

**Comment by RubenDijk** [comment]
Maybe you can use something from here: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component
to fix the problem. There component works fine in the latest HA version.

**Comment by etmjveg** [comment]
Rob, just to let you know this integration is highly appreciated by many. Including myself, not able to code, but happy to debug and test to get this issue resolved. 
Grtz
John

**Comment by raybo2701** [comment]
> Maybe you can use something from here: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component to fix the problem. There component works fine in the latest HA version.

yes. that worked. Nefit easy up and running again.

**Comment by spoetnik** [comment]
Okay. I fixed this, but I don't know if it's the best solution....

Step 1) I forked aionefit, updated slixmpp, and pushed the updated version to pypi https://pypi.org/project/aionefit-updated/

This feels bad, because all I did was updated the slixmpp version, and suddenly I am the maintainer of the working version of aionefit. I am not that good of a Python programmer to maintain this package for real...

step 2) Update ha-nefiteasy to use ```aionefit-updated==0.15``` instead of ```aionefit == 0.14```

I am glad I got this working again. I monitor the pressure in my heating system, and measure my gas consumption using this integration.

**Comment by RobBie1221** [comment]
You can make a pull request here to update the library. If it works, at least for now we can help people.

On the long term I can make a new lib and maintain it, but I currently don’t have time to do that.

**Comment by William-66** [comment]
For HASSIO users I have a temporary solution to get Nefit Easy working again:

1. Download latest slixmpp version (1.8.2) from this [link](https://github.com/poezio/slixmpp)
2. From the downloaded slixmpp-master.zip file extract the slixmpp directory
    and copy it to your HA /config/temp/ directory
3. Login using SHH
4. Run next commands to update your slixmpp library to latest version: 
docker exec -it homeassistant /bin/bash
cd /usr/local/lib/python3.10/site-packages
cp -a /config/temp/slixmpp .
5. Restart HA

NOTE: You need to repeat this after every update of HA !!!

**Comment by etmjveg** [comment]
> For HASSIO users I have a temporary "quick and dirty" fix to get Nefit Easy working again:
> 
> 1. Backup your HA first
> 2. Download latest slixmpp version (1.8.2) from this [link](https://github.com/poezio/slixmpp)
> 3. From the downloaded slixmpp-master.zip file extract the slixmpp directory
>    and copy it to your HA /config/temp/ directory
> 4. Login using SHH
> 5. Run next commands to update your slixmpp library to latest version:
>    docker exec -it homeassistant /bin/bash
>    cd /usr/local/lib/python3.10/site-packages
>    cp -a /config/temp/slixmpp .
> 6. Restart HA
> 
> NOTE: You need to repeat this after every update of HA !!!

Tnx William, workarounds do not come easier than this ;)
Unfortunately I am on HASS-OS. Any thoughts if I can tweak the used library there in a similar way ?

tnx
John

**Comment by RobBie1221** [comment]
Of you wait till this evening, you can update to latest version which will automatically pickup latest slixmpp library.

**Comment by William-66** [comment]
Nice solution, the update works great !!! 👍

**Comment by RobBie1221** [comment]
Fixed in #161

**Comment by pjannink** [comment]
Do not see the update in HACS yet. Any idea when it will be there??

**Comment by RobBie1221** [comment]
I published a release 26 minutes ago (v0.3.0). Should be visible now.

**Comment by pjannink** [comment]
HACS shows v2.3.0 but when opted for redownload v0.3.0 popped up. Thanks all for the quick fix. Works as a charm again!!

**Comment by delcara** [comment]
Updated and works perfectly again!! Thanks all for the effort and good work! No I can limit the hot water time in the shower again. Almost a necessity with the gas prices nowadays :(.

**Comment by JonOve** [comment]
The integration works again after the update!! Much appreciated!!
