### ISSUE TITLE
My Nefit is not feeling Easy anymore after latest HA core update

### ISSUE THREAD

**Issue by KYHS-BOX** [ksya/ha-nefiteasy#155]
hope the lib will be replaced.

**Comment by KYHS-BOX** [comment]
same as https://github.com/ksya/ha-nefiteasy/issues/153

**Comment by KYHS-BOX** [comment]
Logger: homeassistant.components.number
Source: components/number/__init__.py:152
Integration: Nummer ([documentation](https://www.home-assistant.io/integrations/number), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+number%22))
First occurred: 17:01:22 (1 occurrences)
Last logged: 17:01:22
custom_components.nefiteasy.models is setting deprecated attributes on an instance of NumberEntityDescription, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.

**Comment by RobBie1221** [comment]
Duplicate
