### ISSUE TITLE
Year total in kWh

### ISSUE THREAD

**Issue by alextud** [ksya/ha-nefiteasy#17]
Thanks for this integration.

Can we have year total consumption be exported as kWh ? 
I need this value to calculate monthly costs. Maybe exposed as a different name.

**Comment by ksya** [comment]
The m3 value can be converted to kWh again. Now the kWh value is converted to m3 by default. Why do you need the value in kWh?

`return "{0:.1f}".format(self._client.data[self._key] * 0.12307692) #convert kWh to m3, for LPG, multiply with 0.040742416`

So kWh value = m3 value / 0.12307692

**Comment by alextud** [comment]
Sounds good. Hope that this constant it will not change :D
