### ISSUE TITLE
No issue, just a big thank you

### ISSUE THREAD

**Issue by smartins4** [ksya/ha-nefiteasy#170]
Rob and others that made the yesterday release possible: thank you for the effort made in achieving this updated release!

(sorry for marking this as an issue, couldn't think of a better place to do it)

**Comment by hroling** [comment]
Thanks from me to.

**Comment by Atari59** [comment]
Thanks from me too

**Comment by RedMeKool** [comment]
Very appreciated, BIG thanks!

**Comment by mwevromans** [comment]
Thanks for the quick fix!!!

**Comment by RobBie1221** [comment]
Thank you all, most credits go to @spoetnik though :-)

Closing this, as it's not really an issue.
