### ISSUE TITLE
Warning on deprected attributes on NumberEntityDescription 

### ISSUE THREAD

**Issue by jorgwonline** [ksya/ha-nefiteasy#172]
Hi, i got this message, any ideas?
Thank you for all the work on this integration by the way!!

Logger: homeassistant.components.number
Source: components/number/__init__.py:152
Integration: Number (documentation, issues)
First occurred: 9:35:29 PM (1 occurrences)
Last logged: 9:35:29 PM

custom_components.nefiteasy.models is setting deprecated attributes on an instance of NumberEntityDescription, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.

**Comment by RobBie1221** [comment]
I guess you are not on the latest version of the integration? This was fixed yesterday.

**Comment by jorgwonline** [comment]
Yes, i just updated; this issue can be closed;  Thanks RobBie1221!
