### ISSUE TITLE
Configure is not possible

### ISSUE THREAD

**Issue by lowieh** [ksya/ha-nefiteasy#176]
My Nefit controller works for several months allright. But from suddenly HA can't configure my nefit.
I have deinstall the integrations en install it again.
After filling in the serial, the access code en the password. I get a popup with minimum en max temp (10 and 28) and degree steps (0.5)
after that popup its dont configure my entity.

the error description is:
custom_components.nefiteasy.models is setting deprecated attributes on an instance of NumberEntityDescription, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.

Anyone an idea what goes wrong?

**Comment by RobBie1221** [comment]
Update to the latest version and try again. The deprecation message is not an issue, but should be gone with the latest version.

**Comment by lowieh** [comment]
Thanks for the rapid reaction.
i tried....it goes further..but now it said.. Not loaded!

**Comment by RobBie1221** [comment]
Could you add some logging? Not just one snippet but the full log?

**Comment by lowieh** [comment]
Of course but there is no link to the logbook...at the first error was there a link
![not loaded](https://user-images.githubusercontent.com/93491614/180749159-11d85efe-df23-437d-ad2d-a49dd4d180f8.jpg)

**Comment by RobBie1221** [comment]
Please check how to enable logging in HA and read the logbook. It’s in the HA docs

**Comment by lowieh** [comment]
Hoi Rob,

Ik probeer het ff op deze manier.
Na de melding heb ik de integratie verwijderd en getracht opnieuw toe te
voegen. Maar krijg nu onderstaande melding.
Fout

Deze integratie ondersteunt geen configuratie via de UI. Als u deze link
van de Home Assistant-website hebt gevolgd, zorg er dan voor dat u de
nieuwste versie van Home Assistant heeft draaien.

Volgens mij draai ik met de nieuwste versie want die update ik altijd
netjes als ik de melding krijg
Versie core-2022.7.6
Type installatie Home Assistant OS

.Groet Louis




Op ma 25 jul. 2022 om 11:45 schreef Rob Bierbooms ***@***.***

**Comment by RobBie1221** [comment]
https://www.home-assistant.io/integrations/logger/

Set debug level on this integration and post the full log.

**Comment by lowieh** [comment]
Thanks for the help. In the mean time i have deinstalled the integration...in Hacs the integration updated and  restart HA and after all reinstalled the integration and that it works!
