### ISSUE TITLE
Unsupported operand type

### ISSUE THREAD

**Issue by TomZegers** [ksya/ha-nefiteasy#19]
Me again. Sorry for nagging again...
This does not affect my setup but maybe for a future release:

File "/config/custom_components/nefiteasy/sensor.py", line 69, in state
    return "{0:.1f}".format(self._client.data[self._key] * 0.12307692) #convert kWh to m3, for LPG, multiply with 0.040742416
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

**Comment by ksya** [comment]
How did you get this error? It appear there was no data (NoneType) which it cannot multiply with 0.12 (float).

**Comment by TomZegers** [comment]
Sorry for the late response. Did not notice your reply. It seems like it only gives this error at start-up. It doesn't pop-up anymore.
