### ISSUE TITLE
Nefit Easy connection fails with "deprecated attributes .... unsupported from HA 2022.10"

### ISSUE THREAD

**Issue by gerardwr** [ksya/ha-nefiteasy#206]
Hi,

I had some problems with the add-on in the past month, worked great before (thanks!) but HA could not connect to the Nefit Easy.

So I installed the add-on again today. Unfortunately I get this error in the logs.

HA installed : 2022.11.

Is there a fix for this?

Kind regards.

> Logger: homeassistant.components.number
> Source: components/number/__init__.py:159 
> Integration: Nummer (documentation, issues) 
> First occurred: 26 november 2022 20:14:54 (1 occurrences) 
> Last logged: 26 november 2022 20:14:54
> 
> custom_components.nefiteasy.models is setting deprecated attributes on an instance of NumberEntityDescription, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.

**Comment by RobBie1221** [comment]
This has been updated quite some time ago. Please use the newest version.

**Comment by gerardwr** [comment]
Yes was discussed here, I missed that. New install fixed my problem, working again. Thanks.

https://github.com/ksya/ha-nefiteasy/issues/152
