### ISSUE TITLE
HA Log: Using slower stringprep, consider compiling the faster cython/libidn one.

### ISSUE THREAD

**Issue by jaspov** [ksya/ha-nefiteasy#209]
Just noticed this in log today
Running HA 2022.12.0 and Nefit Easy v3.0

Googled and found similar issues on other integrations. General advice was that it's no big deal an can be ignored. Not sure if the same applies here so thought I would post here. Also if this can be ignored, is there a way to keep this from popping up in the log?

Using slower stringprep, consider compiling the faster cython/libidn one.
7 December 2022 at 23:10:25 – (WARNING) Nefit Easy Bosch Thermostat (custom integration)

**Comment by RobBie1221** [comment]
See #67 #69 

It’s not a big issue, it cannot be muted as far as I know and it needs to be solved in slixmpp.
