### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by pjannink** [ksya/ha-nefiteasy#225]
I run HA 2023.2 in Docker on Synology. Log shows following error:
Logger: slixmpp.stringprep
Source: custom_components/nefiteasy/__init__.py:10
Integration: Nefit Easy Bosch Thermostat ([documentation](https://github.com/ksya/ha-nefiteasy), [issues](https://github.com/ksya/ha-nefiteasy/issues))
First occurred: 16:53:54 (1 occurrences)
Last logged: 16:53:54
Using slower stringprep, consider compiling the faster cython/libidn one.

**Comment by RobBie1221** [comment]
See https://github.com/ksya/ha-nefiteasy/issues/67 https://github.com/ksya/ha-nefiteasy/issues/69 https://github.com/ksya/ha-nefiteasy/issues/209 #216
