### ISSUE TITLE
Unclear what is needed for access

### ISSUE THREAD

**Issue by tdijkstra** [ksya/ha-nefiteasy#229]
Hi,

I just got the nefit easycontrol device and I'm trying to get it to work with your software.
For the app to work I had to register the device on the Bosch website, there it now lists it with a "Serial number/gateway-ID" and "Access code/Password"

Your integration ask for Serial Number, Access Key and Password. It seems I have one piece of information to little. I tried the password to the Bosch portal itself, but that doesn't seem to work.
I did see a notice that they recently changed the password-procedure, also the app was updated a few days ago. Maybe your software needs an update?

Thanks for any help,

Tim

**Comment by RobBie1221** [comment]
Did you remove the spaces from the "Access Key" that you entered? Nefit generally displays this with spaces, the integration can't handle that.

**Comment by tdijkstra** [comment]
Yes, on https://devices.bosch-homecom.com/nl/external it doesn't show with spaces actually. So you confirm that the third entry I have to fill-in in the HASS dialog is the password to that website? This single sign-on thingy from bosch?

**Comment by RobBie1221** [comment]
Wait, you have a Bosch Easycontrol CT-200?

This integration is for the Nefit Easy.

**Comment by RobBie1221** [comment]
See also #61

**Comment by tdijkstra** [comment]
Ah, sorry for the confusion!
