### ISSUE TITLE
[Question] Give heating control back to the program

### ISSUE THREAD

**Issue by AdeZwart** [ksya/ha-nefiteasy#236]
When we are all away I have HA set the temperature to 15 degrees. I've been trying to find a way to give temp control back to the regular program, so it starts following the regular schedule when we come back home. I'd prefer to have it following the configured schedule over just setting a higher temp from HA as soon as we arrive.

Does anyone know of a way to revert back to the regular program?

**Comment by RobBie1221** [comment]
I think if you set the mode first to manual and then immediately after back to automatic, it will pick up the temperature from the program.

**Comment by AdeZwart** [comment]
Thanks for the super quick reply! 

I ran a quick manual test and it seems to do the trick! I will probably switch the mode to 'Manual' directly when we leave and the temp is set lower, so I only have to toggle it back to 'Clock' (for automatic) when we get back.
