### ISSUE TITLE
Frequent disconnects

### ISSUE THREAD

**Issue by pathia** [ksya/ha-nefiteasy#243]
I am experiencing frequent disconnects with the nefit (bosch) cloud. Sometimes every few hours. 
I've read a fix for during boot up but not for this specific.
My home automation is a mess with tests and such to make it work reliable.
Is there anything I can do to fix this issue? I don't understand why it is doing this. My internet is super stable and also ha is hard wired.
Could it have something to do with the fact that I also have the nefit easy app on my phone doing its updates in the background and I do too much updates per specific period?

**Comment by pathia** [comment]
Hi Robbie,
That would indeed be the cleanest fix.
I sometimes have multiple disconnects per hour. The worst part for me is that my commands to turn up the temperature in the morning does not always arrive at my Nefit heater so the house is cold in the morning. I guess buffering these commands is also not easy to implement....
![afbeelding](https://user-images.githubusercontent.com/126187/229868017-8fc8a190-f7be-4866-b8c2-b45ec1fb5aca.png)

**Comment by RobBie1221** [comment]
I have no clue what influences the behavior. Multiple times an hour seems a lot. How is your WiFi thermostat connection? I think it actually tries to reach that endpoint to get data.

You could try this branch:
https://github.com/RobBie1221/ha-nefiteasy/tree/refactor_init

I think as to the normal flow it’s pretty much done. The thing not done is to start a reauth flow when you change credentials, but as long as you don’t change them you shouldn’t trigger this.

**Comment by pathia** [comment]
I could always try, indeed. 
I tried enabling the beta version in HACS but unfortunately I cannot see this branch, I guess. Or do I need to select 'dev' ?

**Comment by pathia** [comment]
And regarding the Wi-Fi connection for the thermostat I think it should be stable. It is on 2.4 GHz and my laptop is on 5 GHz only. But I can add some monitoring where I ping the thermostat.
I wasn't aware that the Bosch cloud is only redirecting to my local thermostat.

**Comment by RobBie1221** [comment]
It won’t work through HACS. For you to be able to pick it up as beta in HACS I first need to merge it here and create a beta release. I don’t want to do that yet, never know how many people have beta enabled and pick it up automatically.

Best way is to download from GitHub after following above link and to ssh to ha and copy it manually.

**Comment by pathia** [comment]
Could just as well be the case yes. I think I will try to write an automation to try and reload the integration whenever it fails. And hopefully one day I can upgrade to the fixed version. Thanks a lot for your help so far!

**Comment by pathia** [comment]
> I think it actually tries to reach that endpoint to get data.

Just as an FYI: Yesterday the Nefit integration was unavailable from about 22u until 4:37. Using local monitoring I found out that my physical thermostat was offline from Wi-Fi for exactly that period. So yes I can confirm it does seem to actually reach out to my thermostat. I see it is connecting to the wrong access point throughout my house. I think this issue can be closed.

**Comment by RobBie1221** [comment]
I dusted off the code that you tried and made it work (it needed rebasing on the current branch). I published a pre-release, you should now be able to pick it up from HACS when looking for beta.

**Comment by pathia** [comment]
Awesome! I installed this 0.4.0beta version and well at least it works for now.
Let's see how it keeps up. Thanks.

**Comment by pathia** [comment]
Unfortunately I have my nefit connection down for 11 hours now but a local ping to the device does work. Is there anything I can do to troubleshoot before I reload the plugin?

**Comment by RobBie1221** [comment]
I just looked, this is a very strange place to get an exception. The connected event is raised, and immediately after it does a `self.nefit.get("/gateway/brandID")` which raises a `NotConnectedError` so apparently it is able to connect however the connection is immediately dropped after 🤷

**Comment by RobBie1221** [comment]
try changing this block in `__init.py__:`

```
if self.connected_state == STATE_CONNECTED:
    self.nefit.get("/gateway/brandID")
    try:
        await asyncio.wait_for(
            self.nefit.xmppclient.message_event.wait(), timeout=29.0
        )
    except asyncio.TimeoutError:
        _LOGGER.debug(
            "Did not get a response in time for testing connection."
        )
    except:  # noqa: E722 pylint: disable=bare-except
        _LOGGER.debug("No connection while testing connection.")
    else:
        self.nefit.xmppclient.message_event.clear()

        # No exception and no auth error
        if self.connected_state == STATE_CONNECTED:
            self.connected_state = STATE_CONNECTION_VERIFIED
```

to

```
if self.connected_state == STATE_CONNECTED:
    try: 
        self.nefit.get("/gateway/brandID")
    except slixmpp.xmlstream.xmlstream.NotConnectedError:
        selct.connected_state == STATE_INIT
        return
    try:
        await asyncio.wait_for(
            self.nefit.xmppclient.message_event.wait(), timeout=29.0
        )
    except asyncio.TimeoutError:
        _LOGGER.debug(
            "Did not get a response in time for testing connection."
        )
    except:  # noqa: E722 pylint: disable=bare-except
        _LOGGER.debug("No connection while testing connection.")
    else:
        self.nefit.xmppclient.message_event.clear()

        # No exception and no auth error
        if self.connected_state == STATE_CONNECTED:
            self.connected_state = STATE_CONNECTION_VERIFIED
```

**Comment by holtkamp** [comment]
Thanks for the swift response!

I added the additional try statement. 

Note you made a typo:

`selct.connected_state == STATE_INIT` => `self.connected_state == STATE_INIT`

Will monitor it and report back

**Comment by lsiecker** [comment]
I have had this problem for a few months now, since I moved to a new home with a Nefit Easy. Just read something on a forum about portforwarding since the bosch server tries to connect to it. So I port forwarded ports 5222 and 5223 (as stated om the forum post) and until now it is still connected! Maybe you can give this a try too
