### ISSUE TITLE
Hassio - warning: Switchdevice deprecated modify NefitSwitch to extend SwitchEntity

### ISSUE THREAD

**Issue by prmfeddema** [ksya/ha-nefiteasy#25]
Not sure whether this is an issue in my configuration or in the ha-nefiteasy code (advise is appreciated) but i guess i'd mention it anyway.

Log Details (WARNING)
Logger: homeassistant.components.switch
Source: components/switch/__init__.py:125
Integration: Switch (documentation, issues)
First occurred: 2 June 2020, 17:18:23 (2 occurrences)
Last logged: 2 June 2020, 17:18:23

SwitchDevice is deprecated, modify NefitSwitch to extend SwitchEntity
SwitchDevice is deprecated, modify NefitHotWater to extend SwitchEntity

**Comment by mories76** [comment]
This is a known issue and has been resolved.
Just update the component to the latest version.
