### ISSUE TITLE
warning ClimateDevice is deprecated, modify NefitThermostat to extend ClimateEntity

### ISSUE THREAD

**Issue by prmfeddema** [ksya/ha-nefiteasy#26]
Log Details (WARNING)
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:547
Integration: Climate (documentation, issues)
First occurred: 2 June 2020, 17:18:23 (1 occurrences)
Last logged: 2 June 2020, 17:18:23

ClimateDevice is deprecated, modify NefitThermostat to extend ClimateEntity

**Comment by mories76** [comment]
This is a known issue and has been resolved.
Just update the component to the latest version.
