### ISSUE TITLE
HA cannot connect to Bosch cloud

### ISSUE THREAD

**Issue by liquid-motion** [ksya/ha-nefiteasy#29]
**Problem**
Even with the changes in place in /etc/ssl/openssl.cnf, Hassio is not able to connect to the Bosch cloud. I keep getting the double notification error on my Raspberry Pi:

Unexpected disconnect of [xxx] with Bosch server. Try to reconnect..
Did not succeed in connecting [xxx] to Bosch cloud after retrying 3 times. Retry in 30 seconds.

This was working for quite some time now, but now all of a sudden the problems are back.

I'm on HA 0.116.4.

**Comment by pitoganzado** [comment]
I'm getting the same behavior even after 0.117.0 upgrade.

**Comment by pitoganzado** [comment]
Fix my issues removing: 

MinProtocol = None
CipherString = DEFAULT

from the file /etc/ssl/openssl.cnf

**Comment by AdeZwart** [comment]
I have the same issue running 0.117.0. A restart of Home Assistant solved it for about a day or so. I'm now trying the approach of @pitoganzado, by removing the suggested config from openssl.cnf.

**Comment by AdeZwart** [comment]
Today it started throwing errors again. So removing the MinProtocol and CipherString worked for 5 days for me.

**Comment by liquid-motion** [comment]
It doesn't work at all for me. With or without the modifications in openssl. What I do notice is that unless the errors are thrown (what is 9 times out of 10 after a reboot again), the integration is working correctly. So maybe the timeout needs to be changed? Or the error is passed along to quickly to Hassio?

**Comment by daveweb** [comment]
Same issue here. Does someone have the answer?

**Comment by liquid-motion** [comment]
Problem still persist in 2020.12.2...

**Comment by MHOMEASS** [comment]
I had this problem for long time. Then I upgraded from RPI3 to RPI4 and that solved it for me.

**Comment by Wollli** [comment]
> 
> 
> I had this problem for long time. Then I upgraded from RPI3 to RPI4 and that solved it for me.

I'M running 2020.12.2 on an RASPI 4 and it does not run at all, always the same error message, with or without openssl 
modification.
May be the used login serial / accesskey / password is somehow wrong ?
May be I misunderstood something because I did not set anywhere the IP of the "EasyControl" ? 
Or is it found by the serial number ? Or how ?

**Comment by ksya** [comment]
> > I had this problem for long time. Then I upgraded from RPI3 to RPI4 and that solved it for me.
> 
> I'M running 2020.12.2 on an RASPI 4 and it does not run at all, always the same error message, with or without openssl
> modification.
> May be the used login serial / accesskey / password is somehow wrong ?
> May be I misunderstood something because I did not set anywhere the IP of the "EasyControl" ?
> Or is it found by the serial number ? Or how ?

This integration is for the Nefit Easy, not the Bosch EasyControl, which is the successor of the Nefit Easy. They probably work with the same tech, but I cannot test it and make it work since I don't have it.

**Comment by liquid-motion** [comment]
> I had this problem for long time. Then I upgraded from RPI3 to RPI4 and that solved it for me.

I ordered a RPI4. Let's see if that will solve my problem.

**Comment by liquid-motion** [comment]
Problem hasn't occured anymore since I switched to rPi4!

**Comment by Salvora** [comment]
I am getting two notifications every time I restart HA.
In addition to that, I am having performance issues. Sometimes, setting temp does not register with the add-on and it goes back to previous value.

I have also noticed that I am getting "boiler cannot transfer heat to central heating" on the nefit status state.

rpi4 8gb
Home Assistant OS 5.10
core-2021.1.5

Tried adding 
MinProtocol = None
CipherString = DEFAULT
to openssl.cnf
but it is not persistant.

Does this even necessary anymore?

**Comment by ksya** [comment]
> I have also noticed that I am getting "boiler cannot transfer heat to central heating" on the nefit status state.

Beware that this is an issue with your boiler! 

Is anyone still having issues?

**Comment by RobBie1221** [comment]
> > I have also noticed that I am getting "boiler cannot transfer heat to central heating" on the nefit status state.
> 
> Beware that this is an issue with your boiler!
> 

It's not even an issue. If you only use thermostatic valves and there is no radiator in need of heat, obviously the boiler cannot transfer heat to central heating. It's a valid state of the system.
If I'm correct, the same message appears when outbound and inbound water have same temperature. Than also no heat is transfered and the boiler goes to a waiting state.

**Comment by Salvora** [comment]
> 
> 
> > > I have also noticed that I am getting "boiler cannot transfer heat to central heating" on the nefit status state.
> > 
> > 
> > Beware that this is an issue with your boiler!
> 
> It's not even an issue. If you only use thermostatic valves and there is no radiator in need of heat, obviously the boiler cannot transfer heat to central heating. It's a valid state of the system.
> If I'm correct, the same message appears when outbound and inbound water have same temperature. Than also no heat is transfered and the boiler goes to a waiting state.

Dear Sir,
What you said totally makes sense. It is just that the message is a little bit negative so I took it as an error.

Regarding OpenSSL setting, does this work?

**Comment by AdeZwart** [comment]
> > I have also noticed that I am getting "boiler cannot transfer heat to central heating" on the nefit status state.
> 
> Beware that this is an issue with your boiler!
> 
> Is anyone still having issues?

Yes. Varying results. Sometimes multiple times a day, sometimes not for a couple of days. Today I don't seem to get it working at all.

**Comment by Salvora** [comment]
Regarding the connection issue:
Around 90 percent of the time, whenever I restart HA, I am getting this parse error with slixmpp

Any idea what it is about?
```
2021-02-20 22:06:13 ERROR (MainThread) [slixmpp.xmlstream.xmlstream] Parse error: b'<?xml version=\'1.0\' encoding=\'UTF-8\'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="wa2-mz36-qrmzh6.bosch.de" id="140rl0jjkb" xml:lang="en" version="1.0"><stream:features><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"></starttls><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>DIGEST-MD5</mechanism></mechanisms><ver xmlns="urn:xmpp:features:rosterver"/></stream:features>'
2021-02-20 22:06:13 ERROR (MainThread) [slixmpp.xmlstream.xmlstream] Parse error: b'<challenge xmlns="urn:ietf:params:xml:ns:xmpp-sasl">cmVhbG09IndhMi1tejM2LXFybXpoNi5ib3NjaC5kZSIsbm9uY2U9ImdFSW9nZUNLUFpxUXJOVkVZTTRHcnI1VC8vWWQxeTE3dVAxY2puUFIiLGNoYXJzZXQ9dXRmLTgsYWxnb3JpdGhtPW1kNS1zZXNz</challenge>'
2021-02-20 22:06:13 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/slixmpp/xmlstream/xmlstream.py", line 521, in _consume_send_queue_before_disconnecting
    self.schedule('Disconnect wait', wait,
  File "/usr/local/lib/python3.8/site-packages/slixmpp/xmlstream/xmlstream.py", line 875, in schedule
    raise ValueError(
ValueError: There is already a scheduled event of name: Disconnect wait
2021-02-20 22:06:13 ERROR (MainThread) [slixmpp.xmlstream.xmlstream] Parse error: b'</stream:stream>'
2021-02-20 22:06:13 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/slixmpp/xmlstream/xmlstream.py", line 521, in _consume_send_queue_before_disconnecting
    self.schedule('Disconnect wait', wait,
  File "/usr/local/lib/python3.8/site-packages/slixmpp/xmlstream/xmlstream.py", line 875, in schedule
    raise ValueError(
ValueError: There is already a scheduled event of name: Disconnect wait
```
