### ISSUE TITLE
HACS: not a valid repository

### ISSUE THREAD

**Issue by snickers2k** [ksya/ha-nefiteasy#31]
<img width="399" alt="Bildschirmfoto 2020-11-21 um 15 29 20" src="https://user-images.githubusercontent.com/5986024/99879618-5f010a00-2c0e-11eb-917f-e5d2601d8345.png">

am i doing something wrong? :/

**Comment by RobBie1221** [comment]
This is an integration, you are trying to add it as addon repository. It's not the correct place.

Do you have HACS installed?

**Comment by ksya** [comment]
Indeed, you should add the repo to HACS, not to "supervisor"/Add ons
