### ISSUE TITLE
Step size thermostat

### ISSUE THREAD

**Issue by sanderlv** [ksya/ha-nefiteasy#359]
Setting step size in the nefite app is possible with 0.1 and HA sees them.

In HA Ican only set 0.5 steps. What's the best way to change that and where?

**Comment by RobBie1221** [comment]
When the integration is added, in the second window you were asked to configure max/min temperature and temperature step. Here you can change the 0.5 to 0.1.

Once configured there is no user friendly way to change this. Either you manually edit your config entry in the .storage folder (if you have to ask how to do that, don't do it) or you have to delete and re-add the integration.

**Comment by sanderlv** [comment]
Tell me what file and where and I'll do it :-)

**Comment by RobBie1221** [comment]
SSH to your Home Assistant, there is a .storage folder, there should be a core.config_entries file. Edit that one and search for Nefit, the rest is pretty self explanatory.

**Comment by sanderlv** [comment]
Done! Thanks so much!
