### ISSUE TITLE
Does not work after update

### ISSUE THREAD

**Issue by michieleke** [ksya/ha-nefiteasy#39]
Unfortunately it does not work anymore after the latest update using Home Assistant 2021.1.1
Overview window is showing Nefit dialog with the text unavailable. A total reinstall did not solve the issue.

**Comment by michieleke** [comment]
Log file is showing the following error:
Logger: custom_components.nefiteasy
Source: custom_components/nefiteasy/__init__.py:377
Integration: Nefit Easy Bosch Thermostat (documentation)
First occurred: 12:52:27 PM (3 occurrences)
Last logged: 12:53:28 PM

Unexpected error fetching nefiteasy data: 'switches'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 144, in async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/nefiteasy/__init__.py", line 377, in _async_update_data
    if "home_entrance_detection" in self._config[CONF_SWITCHES]:
KeyError: 'switches'

**Comment by ksya** [comment]
Please update the component. If that doesn't work. Remove the integration from the integrations page and reconfigure again.

**Comment by michieleke** [comment]
Update does not work, same with removing the intgration and doing a reconfigure. I even tried it on a bare home assistant configuration not having hacs/nefit easy integration installed before.

**Comment by ksya** [comment]
Do you use the latest Github code?

**Comment by michieleke** [comment]
I manually deleted all nefit-easy files from docker and downloaded/copied the files from github to the same location in docker and modified the configuration.yaml manually. Now it works. It's not clear to me why the the install via HACS fails.

**Comment by Mysticsilent** [comment]
Had the same issue after update to Home Assistant 2021.1.1 the entities were showing unavailable.
Uninstalled the integration, copied latest Git directory over and manually added configuration and secrets to yaml files.
Afterwards it started working again.

**Comment by ksya** [comment]
Right now the integration can be added from the integrations UI page. confgiuration.yaml is ignored and only imported the first time the new version is loaded.
