### ISSUE TITLE
Compatibilty with Bosch Easy Control

### ISSUE THREAD

**Issue by mkoninkx** [ksya/ha-nefiteasy#4]
Hi Ksya,

First of all, thanks for all the work you've put in the component!

I used your component without problems on a Nefit Easy Control, but I switched to the Bosch Easy Control recently. Can you please confirm if your component should work with this thermostat?

I'm having issues setting it up.
Here's a link to the forum post i've made:
https://community.home-assistant.io/t/nefit-easy-client/8148/187?u=mkoninkx

Thanks in advance!

**Comment by ksya** [comment]
Hi, this component does not work with this product. It is completely different unfortunately!
