### ISSUE TITLE
Home entrance detection is broken

### ISSUE THREAD

**Issue by ksya** [ksya/ha-nefiteasy#45]

**Comment by RobBie1221** [comment]
I'll fix this next, it's not making entities anymore. We need some changes to make sure the endpoints are not fetched when entities are disabled.

**Comment by RobBie1221** [comment]
@ksya Is the home entrance detection endpoint writable? I thought it was only reporting whether it detects users?

If it's only readable, I suggest to change it from switch type to device_tracker type, that could display either "Home" or "Away".

**Comment by ksya** [comment]
I have no idea, never used it. It was implemented by someone else:
https://github.com/ksya/ha-nefiteasy/pull/9

**Comment by RobBie1221** [comment]
Never mind, it's writable. You can apparently override presence with the switch.
