### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by MHOMEASS** [ksya/ha-nefiteasy#5]
First of all thank you for this awsome functionality! I installed it a few days ago and for me it work flawless! I use al the sensors there are available but I only miss one and thats the return tempature. Is it possible to ad this one? 

I live in the Netherlands and winter is coming. Knowning the return tempature is a big plus because with that information I can manualy adjust the supply tempature for the best efficiency of the CV. The bigger the difference between the supply en return tempature the higher the efficiency.

**Comment by ksya** [comment]
Hi, unfortunately this is not available from the Nefit Easy API (as far as I know).
A list of endpoints can be found here: 
https://github.com/robertklep/nefit-easy-core/wiki/List-of-endpoints
and
https://github.com/marcelrv/nefit_easy_protocol/blob/master/Endpoints.md
