### ISSUE TITLE
Integration Nefit not in the list

### ISSUE THREAD

**Issue by MijnGedacht** [ksya/ha-nefiteasy#52]
Hi,

Running HASSIO 2021.2.3 on RPI3b+.
Using Nefit Easy already for long time and always update to the latest version. 
I'm not using HACS, but always update by copying the code to custom_components/nefiteasy/ folder.

According to the "read.me" Configuration section, it should be possible to add the config via Integrations now.
However Nefit doesn't showup in the list when trying to add it. 
Am I missing something ?

Also in the "read.me" Installation section, it's not "explained below" how to add NefitEasy to your configuration.yaml.

**Comment by RobBie1221** [comment]
The description how to use `configuration.yaml` is removed because it's legacy. For existing users, the keys are imported once and after import the entry can be removed because it's not used anymore.

Could you perhaps try to explicitly refresh the integrations page? Maybe it's a cache issue?

**Comment by MijnGedacht** [comment]
Finally was able to add the new Nefit config. 

- Deleted/refreshed browser cash, but Nefit still not showed up in the Integration list  
- I completely removed Nefit from configuration.yaml, also deleted the custom_components/nefiteasy/ folder.
- Did a reboot of my RaspberryPi
- Added Nefit again to configuration.yaml
- Added the new Nefit code again to the custom_components/nefiteasy/ folder
- Checked configuration (under Configuration - Server controls - Configuration Validation) --> OK
- Restarted Home Assistant (under Configuration - Server controls - Server Management)
- Nefit component working again, now also automatically added under Integrations 👍 
- Sensors and switches have other names now, also had to change all these names in automations, lovelaceUI etc...

Thanks for help
