### ISSUE TITLE
Unable to configure on Synology

### ISSUE THREAD

**Issue by Cyclone47** [ksya/ha-nefiteasy#55]
I have a synology running on the latest DSM 7. 
Installed using HACS.

When trying to add the Nefit Integration and entering my details
123 456 789
aaaa bbbb cccc dddd
1234ab123 

I have censored the details, but in this format I have added it.

It then gets stuck adding with an spinning circle 
![image](https://user-images.githubusercontent.com/15861318/110136579-24dc0280-7dd0-11eb-9923-a177f860f61d.png)

Getting this and then it fails with an unknown error
![image](https://user-images.githubusercontent.com/15861318/110136840-75536000-7dd0-11eb-95b2-7ce946b5a6f3.png)

![image](https://user-images.githubusercontent.com/15861318/110136768-5e147280-7dd0-11eb-864c-536166e45cbb.png)

Any idea how to resolve this?

**Comment by RobBie1221** [comment]
Did you read the note in the readme w.r.t. openssl?

**Comment by Cyclone47** [comment]
> Did you read the note in the readme w.r.t. openssl?

Hi,

I did, and did change it on the synology. Or should I change it in the docker terminal? 
If so, should I add both lines? Because they are not there.

**Comment by Cyclone47** [comment]
Actually, my bad. I should have changed it in the docker. /facepalm. It works now!
