### ISSUE TITLE
No entity available

### ISSUE THREAD

**Issue by Cyclone47** [ksya/ha-nefiteasy#57]
I have succesfully managed to install the Nefit Easy integration using the documentation from README.
The integration is showing up in both HACS and Default integrations.
I have entered the correct details upon installing, however I cannot find a single entity when I'm trying to add it to my overview.

Any way to troubleshoot this? It's running on 

- Synology with DSM7
- Home Assistant core-2021.3.1
- HACS: Integration version: | 1.11.3
- HACS: Frontend version: | 20210214110032

**Logs:**
> Logger: homeassistant.config_entries
> Source: custom_components/nefiteasy/__init__.py:169
> First occurred: 10:07:08 PM (1 occurrences)
> Last logged: 10:07:08 PM
> 
> Error setting up entry 000 000 000 for nefiteasy **(masked for privacy reasons)**
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/slixmpp/stringprep.py", line 55, in nodeprep
>     return _nodeprep(node)
>   File "/usr/local/lib/python3.8/site-packages/slixmpp/util/stringprep_profiles.py", line 145, in profile
>     prohibit_output(data, prohibited)
>   File "/usr/local/lib/python3.8/site-packages/slixmpp/util/stringprep_profiles.py", line 78, in prohibit_output
>     raise StringPrepError("Prohibited code point: %s" % char)
> slixmpp.util.stringprep_profiles.StringPrepError: Prohibited code point:  
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/slixmpp/jid.py", line 86, in _validate_node
>     node = nodeprep(node)
>   File "/usr/local/lib/python3.8/site-packages/slixmpp/stringprep.py", line 57, in nodeprep
>     raise StringprepError
> slixmpp.stringprep.StringprepError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
>     result = await component.async_setup_entry(hass, self)  # type: ignore
>   File "/config/custom_components/nefiteasy/__init__.py", line 106, in async_setup_entry
>     client = NefitEasy(hass, credentials)
>   File "/config/custom_components/nefiteasy/__init__.py", line 169, in __init__
>     self.nefit = NefitCore(
>   File "/usr/local/lib/python3.8/site-packages/aionefit/__init__.py", line 45, in __init__
>     self.xmppclient = NefitXmppClient(jid=self.jid,
>   File "/usr/local/lib/python3.8/site-packages/aionefit/provider/slixmpp_impl.py", line 15, in __init__
>     slixmpp.ClientXMPP.__init__(self, jid, password,
>   File "/usr/local/lib/python3.8/site-packages/slixmpp/clientxmpp.py", line 70, in __init__
>     BaseXMPP.__init__(self, jid, 'jabber:client', **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/slixmpp/basexmpp.py", line 58, in __init__
>     self.requested_jid = JID(jid)
>   File "/usr/local/lib/python3.8/site-packages/slixmpp/jid.py", line 323, in __init__
>     self._node, self._domain, self._resource = _parse_jid(jid)
>   File "/usr/local/lib/python3.8/site-packages/slixmpp/jid.py", line 68, in _parse_jid
>     node = _validate_node(node)
>   File "/usr/local/lib/python3.8/site-packages/slixmpp/jid.py", line 88, in _validate_node
>     raise InvalidJID('Nodeprep failed')
> slixmpp.jid.InvalidJID: Nodeprep failed
> 
>

**Comment by Cyclone47** [comment]
Does anyone have a clue how to get this fixed?

**Comment by RobBie1221** [comment]
The error seems to happen in slixmpp...
Note that the config flow simply makes a config entry, it does not check connection so basically it doesn't work at all. Did you use spaces in the serial and access key? If I'm correct, it should not contain spaces.

**Comment by Cyclone47** [comment]
> The error seems to happen in slixmpp...
> Note that the config flow simply makes a config entry, it does not check connection so basically it doesn't work at all. Did you use spaces in the serial and access key? If I'm correct, it should not contain spaces.

Hi @RobBie1221,

Thanks for your response.
I did use spaces similar to how I used it in the nefit app. I will try without spaces and update this issue.

**Comment by Cyclone47** [comment]
@RobBie1221 That did the trick! Might be good to add that to the documentation! :)

Thanks!

**Comment by grmblmmmbl** [comment]
@RobBie1221 @ksya I agree - might be good to add to documentation.

**Comment by RobBie1221** [comment]
I'll do one better, I will change it that the code removes spaces when entering with spaces.

**Comment by WillyWemos** [comment]
That thit the trick thanx
