### ISSUE TITLE
Request: activate shower timer

### ISSUE THREAD

**Issue by jaspov** [ksya/ha-nefiteasy#58]
Thanks for a great plugin. I wonder if it would be able to activate the shower timer via the plugin?

The shower timer function in the nefit app resets, so you have to set it every time prior to a shower. Would be great to have a script in HA that activates it say every 10 minutes via this script if feasible. 

I have no clue if this can be done, thought I’d ask.

**Comment by RobBie1221** [comment]
Seems like there is an easy endpoint to get the status of the shower timer:
/dhwCircuits/dhwA/extraDhw/status
Adding it could be easy.

**Comment by spoetnik** [comment]
`alias: Activate shower timer
description: ""
trigger:
  - platform: state
    entity_id:
      - switch.shower_timer
    from: "on"
    to: "off"
condition: []
action:
  - type: turn_on
    device_id: ca6d276d8e7e0a3cf0d69d033ea827e1
    entity_id: switch.shower_timer
    domain: switch
  - device_id: ca6d276d8e7e0a3cf0d69d033ea827e1
    domain: number
    entity_id: number.shower_timer_duration
    type: set_value
    value: 8
mode: single`
