### ISSUE TITLE
Version key in manifest file

### ISSUE THREAD

**Issue by JCPvanHooren** [ksya/ha-nefiteasy#59]
Custom integrations without `version` key in their manifest file will be blocked from loading starting with Home Assistant 2021.6.

This is announced in the [Breaking Changes](https://www.home-assistant.io/blog/2021/04/07/release-20214/#breaking-changes) for Home Assistant Core 2021.4:

> **Custom integrations: Version warning**
> 
> Custom integrations now require a version key in their manifest file, this also means that all custom integrations now require a manifest file.
> 
> If you are using a legacy custom integration like `custom_components/awesome.py` this now needs to move to `custom_components/awesome/__init__.py` so you can add `custom_components/awesome/manifest.json` to it.
> 
> For more information about integration, manifests have a look here: https://developers.home-assistant.io/docs/creating_integration_manifest
> 
> **For now, this will create a warning on startup.** But this will be blocked from loading if it’s missing a version in the manifest starting with Home Assistant 2021.6.

**Comment by RobBie1221** [comment]
See #53
