### ISSUE TITLE
Installation as add-on repository failed

### ISSUE THREAD

**Issue by kavermeer** [ksya/ha-nefiteasy#60]
I tried to install ha-nefiteasy as an add-on repository. Unfortunately, nothing happened except that this showed up in the log file:

`
21-04-09 20:13:58 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/ksya/ha-nefiteasy repository
21-04-09 20:13:59 ERROR (MainThread) [supervisor.store] https://github.com/ksya/ha-nefiteasy is not a valid add-on repository
21-04-09 20:13:59 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.CORRUPT_REPOSITORY - ContextType.STORE / 68595fea
21-04-09 20:13:59 INFO (MainThread) [supervisor.resolution.module] Create new suggestion SuggestionType.EXECUTE_REMOVE - ContextType.STORE / 68595fea
21-04-09 20:13:59 WARNING (MainThread) [supervisor.store.data] No repository information exists at /data/addons/git/68595fea
21-04-09 20:13:59 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove
21-04-09 20:13:59 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: 68595fea
21-04-09 20:13:59 INFO (MainThread) [supervisor.store.git] Removing custom add-on repository https://github.com/ksya/ha-nefiteasy
`

Did I press the wrong button? Would appreciate any help!

**Comment by RobBie1221** [comment]
See #31 #32 and #49

**Comment by kavermeer** [comment]
Thanks for the quick action. My apologies, I missed that!

**Comment by RobBie1221** [comment]
Np
