### ISSUE TITLE
How to set target temp with action

### ISSUE THREAD

**Issue by one-cyber-camel** [ksya/ha-nefiteasy#64]
Hi, thanks for your work on this integration.

I have successfully installed the integration, I see the climate control on the overview. I can also set the temperature.
I am unable to create an automation with an action which sets the temperature to a certain value.

Hopefully someone can explain how I can achieve this.

Thanks.

**Comment by RobBie1221** [comment]
Use call service and then climate: set temperature

**Comment by one-cyber-camel** [comment]
cool, going to try that out. thanks for a quick response.

**Comment by one-cyber-camel** [comment]
Excellent, already working. New to HA, so couldn't find it. Thanks again, really cool to control the Nefit with this.
👍🏻
