### ISSUE TITLE
Issue after upgrading to Home Assistant 2021.06.0

### ISSUE THREAD

**Issue by pjannink** [ksya/ha-nefiteasy#66]
Integration can not be loaded suddenly. Please assist
Message:

 Logger: homeassistant.setup
Source: setup.py:172
First occurred: 11:02:19 AM (1 occurrences)
Last logged: 11:02:19 AM
Setup failed for nefiteasy: Integration not found.

**Comment by Psol0912** [comment]
Have the same problem , 
Is there nos support for it ,in the update?

**Comment by RobBie1221** [comment]
Are you all using the latest version which has a version number in the manifest file?

**Comment by Psol0912** [comment]
I have updated the version with the number in the manifest file . And now it works, Thnx

**Comment by RobBie1221** [comment]
@pjannink Make sure to run the latest version.

**Comment by pjannink** [comment]
Thx. This works
