### ISSUE TITLE
Getting: Using slower stringprep, consider compiling the faster cython/libidn one.

### ISSUE THREAD

**Issue by sanderlv** [ksya/ha-nefiteasy#67]
Is it possible to get this resolved:
```

Logger: slixmpp.stringprep
Source: /usr/local/lib/python3.8/site-packages/slixmpp/stringprep.py:120
First occurred: 19:54:06 (1 occurrences)
Last logged: 19:54:06

Using slower stringprep, consider compiling the faster cython/libidn one.
```

**Comment by RobBie1221** [comment]
Perhaps, but not here. The `slixmpp` is used by `aionefit`, which is used by this integration. This needs to be solved upstream by `slixmpp` and then a new version needs to be pinned to `aionefit`, I suggest you create an issue in one of those projects.

**Comment by sanderlv** [comment]
> This needs to be solved upstream by `slixmpp` and then a new version needs to be pinned to `aionefit`, I suggest you create an issue in one of those projects.

Good suggestion! Where is that?

**Comment by RobBie1221** [comment]
I would start here: https://github.com/marconfus/aionefit

I see that version 1.5.1 of slixmpp is pinned, there is a newer version available anyway, maybe it's already fixed.

**Comment by EvEvans** [comment]
> I would start here: https://github.com/marconfus/aionefit
> 
> I see that version 1.5.1 of slixmpp is pinned, there is a newer version available anyway, maybe it's already fixed.

@RobBie1221 The repository you linked (aionefit) now has been archived, so this won't be fixed from there. Any other suggestions about how this can be resolved?

Just for reference, the error message with the newest python installed (3.10) now reads:

>  Logger: slixmpp.stringprep
> Source: /usr/local/lib/python3.10/site-packages/slixmpp/stringprep.py:114
> First occurred: 13:03:26 (1 occurrences)
> Last logged: 13:03:26
> Using slower stringprep, consider compiling the faster cython/libidn one.
