### ISSUE TITLE
Using slower stringprep, consider compiling the faster cython/libidn one.

### ISSUE THREAD

**Issue by JCPvanHooren** [ksya/ha-nefiteasy#69]
I keep getting this warning in my logs and can only relate it to my Nefit Easy integration in Home Assistant.
Am I right this may be triggered by this integration?
Is there a way to resolve?

Logger: slixmpp.stringprep
Source: /usr/local/lib/python3.9/site-packages/slixmpp/stringprep.py:120
First occurred: 19:31:29 (1 occurrences)
Last logged: 19:31:29

Thanks

**Comment by RobBie1221** [comment]
See #68

**Comment by RobBie1221** [comment]
Sorry, meant #67

**Comment by danielbrunt57** [comment]
How did you narrow it down to this integration?
I too am getting the error but I'm not using the Nefit Easy integration...
