### ISSUE TITLE
Feature request: Make compatible with HACS

### ISSUE THREAD

**Issue by MarcHagen** [ksya/ha-nefiteasy#7]
~~https://custom-components.github.io/hacs/developer/general/~~

**Comment by marklagendijk** [comment]
https://hacs.xyz/docs/publish/start

**Comment by ksya** [comment]
I'm busy with integration into the main home assistant, so this won't be necessary. If it takes too long for you, you might do it yourself and create a pull request.

**Comment by MarcHagen** [comment]
That’s perfect to! Thank you
