### ISSUE TITLE
No option to add custom repo

### ISSUE THREAD

**Issue by ChristianVerhoeven** [ksya/ha-nefiteasy#73]
Hi,

Your documentation says to add the repo using settings, but there is no settings. How do I add your Nefit Easy support to Home Automation (6.2)?

**Comment by RobBie1221** [comment]
Home Automation 6.2?

**Comment by ChristianVerhoeven** [comment]
- Home Assistant OS 6.2
- supervisor-2021.06.8
- core-2021.8.7

**Comment by RobBie1221** [comment]
Ok, so if you want to add it automatically to Home Assistant, you will beed HACS. Do you have this installed?

**Comment by ChristianVerhoeven** [comment]
No I have not installed HACS

**Comment by RobBie1221** [comment]
Once you have HACS, you can add this repo.

**Comment by ChristianVerhoeven** [comment]
Is this the only way to use your custom intergration?

**Comment by RobBie1221** [comment]
No, the alternative is to manually copy the sources to config/custom_components folder
