### ISSUE TITLE
Add Gas Usage and an Energy gas source

### ISSUE THREAD

**Issue by bsimmo** [ksya/ha-nefiteasy#74]
HA now has an Energy Panel and has added Gas usage, 
Use the Wave year total as a statistic so it can be use*

https://www.home-assistant.io/blog/2021/09/01/release-20219/#keeping-track-of-your-gas-usage

Docs tell me to tell you to look here.  To be fair this could be used for temperatures etc too.
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

```
e.g.
    "year_total": {
        name: "Year total",
        url: "/ecus/rrc/recordings/yearTotal",
        unit: "m³",
        icon: "mdi:gas-cylinder",
        state_class: "total_increasing",
        device_class: "gas",
    },
```

*it may of course be more complicated than that.
Yearly may be a problem as it is yearly-cumulative, but can worry about that each year ;-)

**Comment by flouwers** [comment]
I would also be interested in such feature.
I think the entity should implement `state_class` and `last_reset` (probably on Jan 1st ?).
Also, I don't know if the unit should be `m³` or `m3`

**Comment by ksya** [comment]
Sorry I cannot test since I don't have the thermostat anymore. It broke last summer.

**Comment by bsimmo** [comment]
> Sorry I cannot test since I don't have the thermostat anymore. It broke last summer.

But we can.
I just can't quite understand how it's all implemented to add state class etc. I tried but failed. 
I believe methods of units are changing too.

**Comment by RobBie1221** [comment]
> I would also be interested in such feature. I think the entity should implement `state_class` and `last_reset` (probably on Jan 1st ?). Also, I don't know if the unit should be `m³` or `m3`

Yes, we should use `last_reset`. As winter season is approaching, I'm planning some improvements. I'll take this with me, but it may take some time.

**Comment by spoetnik** [comment]
```
friendly_name: Nefit Year total
icon: mdi:gas-cylinder
unit_of_measurement: 'm³'
state_class: 'total_increasing'
device_class: 'gas'
```

**Comment by RobBie1221** [comment]
You can try out latest version. It's not released yet, I'm not sure how that shows up in HACS if you use that.

Let me know if this works for you, if so I'll create an official release.

**Comment by spoetnik** [comment]
The Nefit Yearly show up as a gas source, but gives an error:
`The state of these configured entities are currently not available:
sensor.year_total (unknown)`

The sensor isn't reporting it's state (value) at the moment....

**Comment by RobBie1221** [comment]
I've noticed that it takes after restarting HA a bit longer for the state to be updated. I need to check why, maybe it has something to do that sensor entity doesn't have state property anymore.

**Comment by RobBie1221** [comment]
> The Nefit Yearly show up as a gas source, but gives an error: `The state of these configured entities are currently not available: sensor.year_total (unknown)`
> 
> The sensor isn't reporting it's state (value) at the moment.... I have added the state manual, to the value I get from the Nefit Easy app. Fingers crossed it updates in Home Assistant. I will let you know
> 
> Thanks for developing this!!

Try again, there was a typo in code I cleaned to make `mypy` happy. See #82, that should solve it.

**Comment by bsimmo** [comment]
If it's working, can you release.  I assume it'll not mess anyone else's setup up.
aka I can't see how you can use test versions using HACS ;-) there is no option that I can see.
I have use beta version ticked, but I', guessing it is not released as a beta (perhaps try that first.) 

Other option I can see are the current v0.1.0 and old v0.0.1 and also master.

**Comment by RobBie1221** [comment]
It has structural changes, so it could mess things up.

I made a prerelease, that should be visible in HACS only if beta version is ticked.

Let me know if it works such that I can promote it to release.

**Comment by bvklingeren** [comment]
I installed the pre-release and I’m very happy with the shower timer. 

In my setup I hide all sensors and switches except specific ones (e.g. system_pressure) in my configuration yaml and I cannot enable year_total there, so I think the new sensors and switches do not work yet with the filter. That’s probably also the reason why I do see the shower entities (they are not filtered as well).

**Comment by RobBie1221** [comment]
Does hide mean disabled?
Since we made a config flow, entities defined in `configuration.yaml` are ignored and they are all added.

One improvement that I plan to make is to disable some specific entities by default (maybe all switches/sensors) such that upon creation they are disabled. Users can then enable the ones they really need. This would prevent unnecessary polling of endpoints.

**Comment by bsimmo** [comment]
Seems to be working for me now it's had time to collect data. Nothing has
broken for me.


Never had boiler pressure ever do anything but 25.5 bar.

In general only have the temps and gas usage since everything else stays
the same (or the phone app does it better) and probably only useful for
automation if people use that.

And no idea what status is meant to say. Always blank for me.

(I'm using a Worcester Wave)

**Comment by bvklingeren** [comment]
> Does hide mean disabled?
> 
> Since we made a config flow, entities defined in `configuration.yaml` are ignored and they are all added.
> 
> 
> 
> One improvement that I plan to make is to disable some specific entities by default (maybe all switches/sensors) such that upon creation they are disabled. Users can then enable the ones they really need. This would prevent unnecessary polling of endpoints.

They are indeed disabled. I will remove the yaml config and try again.

**Comment by bvklingeren** [comment]
Hmm, I think I just forgot to remove the config before when config flow was introduced. Removing the config did nothing, I just enabled the year_total entity in the entity details screen an it worked. It's now being updated.
Thanks for the great work!

**Comment by RobBie1221** [comment]
Once import is done, entries in `configuration.yaml` are ignored. As of next release import is completely removed, as the changes I made were incompatible with existing yaml configuration. 

I'll make an official release in the coming days.
