### ISSUE TITLE
Reported Temperature entity

### ISSUE THREAD

**Issue by bsimmo** [ksya/ha-nefiteasy#75]
I can see climate.wave as a thermostat, but that doesn't provide logging or individual temp (unless I'm missing something).
Can sensor.wave_room_temperature be added as a seperte entity.
With it's logging

```
    "indoor_temperature": {
        name: "Outdoor temperature",
        url: "no_idea_of_location",
        unit: "°C",
        device_class: "temperature",
        state_class: "measurement",
    },
```

I think it needs last_update to be available as a sensor too which all sees to be wound up in climate.wave at the moment
```
    "indoor_temperature": {
        name: "time_stamp",
        url: "no_idea_of_location",
        unit: "ISO8601",
        device_class: "timestamp",
    },
```

**Comment by ksya** [comment]
You can use a template sensor entity for this.

**Comment by bsimmo** [comment]
No idea how to do that, but had a play in the template in dev section and everytime I typed climate.wave it showed an error.
Seems a bit beyond me at the moment.  Having a play with the python files but seems state_class isn't implemented and errors with them added.

**Comment by steierc** [comment]
i have added the following to  const.py

`   "room_temperature": {
        name: "Room temperature",
        url: "/heatingCircuits/hc1/roomtemperature",
        unit: TEMP_CELSIUS,
        device_class: "temperature",
    },
    `
This seems to have done the trick and I am now presented with a "Room Temperature" Sensor

**Comment by ksya** [comment]
Please make a template sensor instead.
Use this:
{{ state_attr('climate.cv', 'current_temperature' ) }}

See also https://www.home-assistant.io/docs/configuration/templating/
