### ISSUE TITLE
Doesn't show up in integrations

### ISSUE THREAD

**Issue by mensand** [ksya/ha-nefiteasy#76]
I've followed the steps via HACS and installed the component. The directory for the custom component is in my installation. So HACS has installed the Nefit Easy component. But when i wan't to activate the integration it isn't there

**Comment by RobBie1221** [comment]
Is this still an issue? If so, could you add some screenshots?

**Comment by RobBie1221** [comment]
Assume this is no longer an issue, if so, add some more info.
