### ISSUE TITLE
Config flow could not be loaded

### ISSUE THREAD

**Issue by DaanBaars** [ksya/ha-nefiteasy#78]
When trying to add the integration im getting this error, in de HA logs i found this:

Logger: homeassistant.config_entries
Source: config_entries.py:563
First occurred: 15:57:29 (1 occurrences)
Last logged: 15:57:29
Error occurred loading configuration flow for integration nefiteasy: cannot import name 'FlowResult' from 'homeassistant.data_entry_flow' (/usr/src/homeassistant/homeassistant/data_entry_flow.py)

**Comment by gerardwr** [comment]
@RobBie1221 

Had the same problem after installing (yesterday) from this (@ksya) Github "Config flow could not be loaded".

When I installed from the Github from your @RobBie1221 Github it installs and runs fine.

Thx.
