### ISSUE TITLE
Changing language

### ISSUE THREAD

**Issue by Dualdriven** [ksya/ha-nefiteasy#85]
Hello,

Setting up went really well using HACS, thanks for all the coding!

I was just wondering would it be possible to change to language? I tried changing same "names" in different .yaml files but without any luck.
Also, I am just starting with HA so it is pretty possible I forgot some things.

Cheers,

Dual

**Comment by RobBie1221** [comment]
You want to change entity names?

**Comment by Dualdriven** [comment]
First off, wow that's a fast answer!

Right, they are called entities. Would be great if it could be named otherwise. Added a picture for extra clarification.
![Knipsel](https://user-images.githubusercontent.com/93786489/140799008-6356328f-ae13-4e7b-bc82-6cbf3f86e3be.PNG)

**Comment by RobBie1221** [comment]
Forget yaml, you can't do anything from there. The entity names can be changed by clicking on it. You should get a  windows where you can change entity id and name.

The status code is a different matter, there is no language support at the moment, so it's English only.

**Comment by Dualdriven** [comment]
Ah, I didn't know I had to reload the card as well. Thanks for your help!

**Comment by RobBie1221** [comment]
Glad to be of help
