### ISSUE TITLE
[Feature] Adding the ability to set temperature from automations

### ISSUE THREAD

**Issue by Atiunderscore** [ksya/ha-nefiteasy#89]
I'm trying to figure out to create an automation that sets the temperature at a certain time, but there are entities missing to do so. 

Example:
At 23:00 set temperature to 15.0 C.
At 10:00 set temperature to 20.5 C.

I would like to have this feature because we sometimes forget to turn down the temperature at night (we are using manual mode).

**Comment by RobBie1221** [comment]
Action type --> Call service
Service --> Climate: Set temperature

Select the nefit climate entity.
