### ISSUE TITLE
Entity climate.nefit (<class 'custom_components.nefiteasy.climate.NefitThermostat'>) implements device_state_attributes. 

### ISSUE THREAD

**Issue by balk77** [ksya/ha-nefiteasy#92]
Hi, I have just installed HA 2021.12.1 and I am receiving this message. Something will break in the future. Can you please take the action needed to resolve this? I have no clue how by the way.
```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 06:13:01 (1 occurrences)
Last logged: 06:13:01

Entity climate.nefit (<class 'custom_components.nefiteasy.climate.NefitThermostat'>) implements device_state_attributes. Please report it to the custom component author.
```

**Comment by RobBie1221** [comment]
Thanks for sharing. I'm not on the newest version so haven't noticed that yet. This needs adjustment to be in line with HA changes.

**Comment by jorgwonline** [comment]
I noticed the same thing today, found the issue already reported here, great Balk77. 

`Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 11:55:09 AM (1 occurrences)
Last logged: 11:55:09 AM

Entity climate.nefit (<class 'custom_components.nefiteasy.climate.NefitThermostat'>) implements device_state_attributes. Please report it to the custom component author.`
