### ISSUE TITLE
Instructions are not complete

### ISSUE THREAD

**Issue by MokSamuel** [ksya/ha-nefiteasy#98]
The instructions state the following:
Installation
1 Copy the folder custom_components/nefiteasy/ to your homeassistant config directory.
2 Add the config to your configuration.yaml file **as explained below.**
3 Restart Home Assistant or Hass.io.

The config for the configuration.yaml file isn't listed anywhere. Could anyone please update the readme with clear instructions for this step?

**Comment by RobBie1221** [comment]
This integration does not support setup through `configuration.yaml`, did you even try the steps?

**Comment by RobBie1221** [comment]
Ah wait...now I see it...

**Comment by RobBie1221** [comment]
Just follow the steps under Configuration, forget about `configuration.yaml`. I'll update the readme.

**Comment by MokSamuel** [comment]
I did get it working through configuration.yaml. I had to do it that way because I'm running without supervisor/HACS. I added the following in configuration.yaml to get it working:

climate:
  platform: nefiteasy
  name: Heating
  serial: '<>'
  accesskey: <>
  password: <>

**Comment by RobBie1221** [comment]
Are you using an old version? That should not work at all.

**Comment by MokSamuel** [comment]
> Are you using an old version? That should not work at all.

I did walk through the configuration steps afterwards to get it working, but the Nefit icon didn't show up in the list of integration before I edited config.yaml. I might have changed 2 things at once though (copying the folder to the correct position maybe?). 

If thats the case my steps were:
1. copy the folder to the correct location 
2. restart
3. configure using the "add integration" button

**Comment by RobBie1221** [comment]
Those steps make sense. If it's in an incorrect folder, it won't show up when you press 'add integration'

You may check the logs w.r.t. the yaml entry, I would expect an error.

**Comment by MokSamuel** [comment]
Seems like the bit I added to config.yaml just doesn't do anything then, even no errors! 
Anyway, it works great, thanks a lot for the replies and the package! Disregarding step 2 in the readme would be sufficient then!

**Comment by RobBie1221** [comment]
Ok, nice you got it working. I updated the readme.

**Comment by ThaChillera** [comment]
To latch onto this issue: the copy step is unclear: `Copy the folder custom_components/nefiteasy/ to your homeassistant config directory.` implies running `cp -a custom_components/nefiteasy/ $CONFIG_FOLDER` - which is incorrect.

Only figured out this issue due to trial & errors copying different folders!

**Comment by RobBie1221** [comment]
So, what exactly is unclear? Using terminal and `cp` is just one way, you could also use ftp to upload files.

**Comment by ThaChillera** [comment]
the required command is `cp -a custom_components/ $CONFIG_FOLDER`, thats where i tripped up. so my config folder contains `custom_components`, which contains `nefiteasy`.
